language: java
jdk:
   - oraclejdk8
cache:
   directories:
      - "$HOME/.m2/repository"
      - "$HOME/.sonar/cache"

# Do integration test on configured servers.
env:
   - SERVER=wildfly-hibernate
   - SERVER=wildfly-eclipselink
   - SERVER=tomee-openjpa
script: mvn verify -Dmaven.javadoc.skip=true -P $SERVER

# Do snapshot deployment.
deploy:
   provider: script
   script: mvn deploy -Dmaven.test.skip -s settings.xml
   skip_cleanup: true
   on:
      branch: develop
      condition: "$SERVER = wildfly-hibernate"
